export type ProjectItem = {
  title: string;
  stack: string;
  desc: string;
  image: string;
  url: string;
  tags: string[];
};

export const projectsData: ProjectItem[] = [
  {
    title: "Animated Landing",
    stack: "Next.js, GSAP",
    desc: "Landing page dengan parallax dan scroll-trigger animations.",
    image: "https://placehold.co/600x400/png?text=Animated+Landing",
    url: "#",
    tags: ["Parallax", "ScrollTrigger", "Accessibility"],
  },
  {
    title: "Dashboard UI",
    stack: "React, Tailwind",
    desc: "Komponen dashboard responsif dengan tema gelap elegan.",
    image: "https://placehold.co/600x400/png?text=Dashboard+UI",
    url: "#",
    tags: ["Charts", "Responsive", "Theme"],
  },
  {
    title: "Portfolio V2",
    stack: "Next.js, TypeScript",
    desc: "Arsitektur modular dengan performa tinggi.",
    image: "https://placehold.co/600x400/png?text=Portfolio+V2",
    url: "#",
    tags: ["Next.js", "TypeScript", "GSAP"],
  },
  {
    title: "Micro-Interactions",
    stack: "GSAP",
    desc: "Animasi hover dan fokus yang halus.",
    image: "https://placehold.co/600x400/png?text=Micro-Interactions",
    url: "#",
    tags: ["Hover", "Focus", "Motion"],
  },
  {
    title: "E-Commerce UI",
    stack: "Next.js, Tailwind",
    desc: "Halaman produk dengan filter dan grid responsif.",
    image: "https://placehold.co/600x400/png?text=E-Commerce+UI",
    url: "#",
    tags: ["E-Commerce", "Filter", "Responsive"],
  },
  {
    title: "Blog Platform",
    stack: "Next.js, MDX",
    desc: "Blog dengan dukungan MDX dan tema gelap.",
    image: "https://placehold.co/600x400/png?text=Blog+Platform",
    url: "#",
    tags: ["MDX", "Dark Mode", "SEO"],
  },
  {
    title: "Analytics Dashboard",
    stack: "React, Chart.js",
    desc: "Visualisasi data real-time dengan animasi halus.",
    image: "https://placehold.co/600x400/png?text=Analytics+Dashboard",
    url: "#",
    tags: ["Charts", "Real-time", "Animations"],
  },
  {
    title: "Travel Gallery",
    stack: "Next.js, Images",
    desc: "Galeri foto dengan lazy loading dan efek grid.",
    image: "https://placehold.co/600x400/png?text=Travel+Gallery",
    url: "#",
    tags: ["Gallery", "Lazy Load", "Grid"],
  },
  {
    title: "Forms Kit",
    stack: "React, Zod",
    desc: "Validasi form yang kuat dengan UX ramah.",
    image: "https://placehold.co/600x400/png?text=Forms+Kit",
    url: "#",
    tags: ["Forms", "Validation", "UX"],
  },
  {
    title: "Animations Lab",
    stack: "GSAP",
    desc: "Kumpulan eksperimen animasi untuk micro-interactions.",
    image: "https://placehold.co/600x400/png?text=Animations+Lab",
    url: "#",
    tags: ["GSAP", "Micro-Interactions", "Experiments"],
  },
  {
    title: "Portfolio V3",
    stack: "Next.js, TypeScript",
    desc: "Refactor performa, aksesibilitas, dan layout.",
    image: "https://placehold.co/600x400/png?text=Portfolio+V3",
    url: "#",
    tags: ["Accessibility", "Performance", "Refactor"],
  },
  {
    title: "AI Chat UI",
    stack: "React",
    desc: "Antarmuka chat dengan streaming dan markdown.",
    image: "https://placehold.co/600x400/png?text=AI+Chat+UI",
    url: "#",
    tags: ["Chat", "Streaming", "Markdown"],
  },
  {
    title: "Music Player",
    stack: "React",
    desc: "Pemutar musik dengan playlist dan visualizer.",
    image: "https://placehold.co/600x400/png?text=Music+Player",
    url: "#",
    tags: ["Audio", "Playlist", "Visualizer"],
  },
  {
    title: "Recipe App",
    stack: "Next.js",
    desc: "Katalog resep dengan pencarian dan filter.",
    image: "https://placehold.co/600x400/png?text=Recipe+App",
    url: "#",
    tags: ["Search", "Filter", "Cards"],
  },
  {
    title: "Task Manager",
    stack: "React",
    desc: "Manajemen tugas dengan drag-and-drop.",
    image: "https://placehold.co/600x400/png?text=Task+Manager",
    url: "#",
    tags: ["Tasks", "DnD", "Productivity"],
  },
  {
    title: "Finance Tracker",
    stack: "React",
    desc: "Pelacakan pengeluaran dengan grafik.",
    image: "https://placehold.co/600x400/png?text=Finance+Tracker",
    url: "#",
    tags: ["Finance", "Charts", "Insights"],
  },
  {
    title: "Weather App",
    stack: "Next.js",
    desc: "Cuaca real-time dengan peta dan animasi.",
    image: "https://placehold.co/600x400/png?text=Weather+App",
    url: "#",
    tags: ["Weather", "Maps", "Realtime"],
  },
  {
    title: "Notes App",
    stack: "React",
    desc: "Catatan dengan tag dan pencarian.",
    image: "https://placehold.co/600x400/png?text=Notes+App",
    url: "#",
    tags: ["Notes", "Tags", "Search"],
  },
  {
    title: "Photo Editor",
    stack: "React",
    desc: "Editor foto sederhana dengan filter.",
    image: "https://placehold.co/600x400/png?text=Photo+Editor",
    url: "#",
    tags: ["Photos", "Filters", "Editor"],
  },
  {
    title: "Kanban Board",
    stack: "React",
    desc: "Papan kanban dengan kolom fleksibel.",
    image: "https://placehold.co/600x400/png?text=Kanban+Board",
    url: "#",
    tags: ["Kanban", "DnD", "Teams"],
  },
  {
    title: "Portfolio Mobile",
    stack: "React Native",
    desc: "Versi mobile dengan navigasi tab dan animasi.",
    image: "https://placehold.co/600x400/png?text=Portfolio+Mobile",
    url: "#",
    tags: ["Mobile", "Tabs", "Animations"],
  },
];